gerrit:
  project: Packages/TYPO3.Fluid
  username: travis-bot
  password: foushag0

github:
  repository: mneuhaus/TYPO3.Fluid
  token: c1c1edb169d834b5c154d301187cfe457eaa71ed

branches:
  - 'master'
  - '2.0'
  - '2.1'
  - '2.2'

travis:
  token: k_BhN2fFmb7GoaT5ig5wKg
  maxBuilds: 2

codeSniffer:
  active: false
  ignore:
    - ProxyClassBuilder.php

rebasePrompt: false